environment: development
host: mecenergia.lappis.rocks

api:
  port: 8000
  secretName: mec-energia-api-secretkey
  image: registry.gitlab.com/lappis-unb/projetos-energia/mec-energia/mec-energia-api:1.0.126

db:
  existingSecret:
    name: "mec-energia-db-connection"
    hostKey: "POSTGRES_HOST"
    portKey: "POSTGRES_PORT"
    databaseKey: "POSTGRES_NAME"
    userKey: "POSTGRES_USER"
    passwordKey: "POSTGRES_PASSWORD"
    versionKey: "POSTGRES_VERSION"

email:
  existingSecret:
    name: "mec-energia-email"
    emailKey: "MEC_ENERGIA_EMAIL"
    passwordKey: "MEC_ENERGIA_EMAIL_APP_PASSWORD"

web:
  port: 3000
  image: registry.gitlab.com/lappis-unb/projetos-energia/mec-energia/mec-energia-web:1.0.450