apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mec-energia-web
  name: mec-energia-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mec-energia-web
  template:
    metadata:
      labels:
        app: mec-energia-web
    spec:
      containers:
        - image: {{ .Values.web.image }}
          name: mec-energia-web
          ports:
            - containerPort: {{ .Values.web.port }}
              hostPort: {{ .Values.web.port }}
              protocol: TCP
      restartPolicy: Always
